### ISSUE TITLE
Images aren't readable???

### ISSUE THREAD

**Issue by Similirity** [AmaliJD/ManiaDash#3]
i imported the project over to unity and fixed some bugs, but now i have no idea how to fix the "Could not create asset from [xyz]: File could not be read"

the sprites dont open with paint.net or anything and when i try to convert the sprites to bmp they give me an error as well. what do i do?

**Comment by AmaliJD** [comment]
You'll need to install git LFS on your machine to have the images loaded into the project from git. So download git lfs, then clone the project, and all the images and other large assets will be there.
