### ISSUE TITLE
We Got a problem!

### ISSUE THREAD

**Issue by Arrhythmiagamer23** [AmaliJD/ManiaDash#4]
There's an error on the code for git & git LFS!
![Screenshot 2024-02-20 110212](https://github.com/AmaliJD/ManiaDash/assets/158773839/a3e691f9-4ea8-434e-8e4c-f457aacbf730)

**Comment by AmaliJD** [comment]
This seems to have been a temporary issue with lootlocker, but if you ever get it again, my fix was deleting the LootLockerManager.cs script from Assets/Scripts/Scrapped/, and also removing the lootlocker dependency from the manifest.json in the Packages folder.
